### ISSUE TITLE
Server Error 500 when adding POS data.  

### ISSUE THREAD

**Issue by Turtle-Head** [evewspace/eve-wspace#197] opened 2015-08-16 15:14 UTC
It would be really awesome if Drug Labs, and other unknown modules wouldn't throw this issue when attempting to add a Dscan of a POS with one anchored or nearby.  If you could add support for the Drug Manufacture modules in the types added to the POS fitting that would be really nice.

**Comment by marbindrakon** [comment] 2015-08-16 18:16
Duplicate of #196

**Closed by marbindrakon** 2015-08-16 18:16 UTC
