### ISSUE TITLE
Issue Adding POS

### ISSUE THREAD

**Issue by Alcynthan** [evewspace/eve-wspace#204] opened 2015-09-20 15:33 UTC
Error: "No POS in the D-scan!" for Auto. "Oops, something broke." for Manual.

D-scan paste below:

Outpost	Angel Control Tower	69 km
Ballistic Deflection Array	Ballistic Deflection Array	71 km
Ballistic Deflection Array	Ballistic Deflection Array	72 km
Ballistic Deflection Array	Ballistic Deflection Array	73 km
Ballistic Deflection Array	Ballistic Deflection Array	73 km
Ballistic Deflection Array	Ballistic Deflection Array	74 km
Ballistic Deflection Array	Ballistic Deflection Array	74 km
Blood Energy Neutralizing Battery	Blood Energy Neutralizing Battery	111 km
Blood Energy Neutralizing Battery	Blood Energy Neutralizing Battery	54 km
Trial 2	Corporate Hangar Array	75 km
Trial 3	Corporate Hangar Array	76 km
Trial 1	Corporate Hangar Array	77 km
Domination Large Artillery Battery	Domination Large Artillery Battery	105 km
Domination Large Artillery Battery	Domination Large Artillery Battery	35 km
Domination Large Artillery Battery	Domination Large Artillery Battery	41 km
Domination Large Artillery Battery	Domination Large Artillery Battery	97 km
Domination Large Artillery Battery	Domination Large Artillery Battery	99 km
Domination Stasis Webification Battery	Domination Stasis Webification Battery	106 km
Domination Stasis Webification Battery	Domination Stasis Webification Battery	63 km
Domination Stasis Webification Battery	Domination Stasis Webification Battery	79 km
Domination Stasis Webification Battery	Domination Stasis Webification Battery	89 km
Explosion Dampening Array	Explosion Dampening Array	70 km
Explosion Dampening Array	Explosion Dampening Array	71 km
Explosion Dampening Array	Explosion Dampening Array	73 km
Explosion Dampening Array	Explosion Dampening Array	74 km
Force Field	Force Field	42 km
Heat Dissipation Array	Heat Dissipation Array	71 km
Heat Dissipation Array	Heat Dissipation Array	72 km
Heat Dissipation Array	Heat Dissipation Array	75 km
Ion Field Projection Battery	Ion Field Projection Battery	100 km
Ion Field Projection Battery	Ion Field Projection Battery	36 km
Ion Field Projection Battery	Ion Field Projection Battery	69 km
Ion Field Projection Battery	Ion Field Projection Battery	82 km
Ion Field Projection Battery	Ion Field Projection Battery	83 km
Ion Field Projection Battery	Ion Field Projection Battery	84 km
Ion Field Projection Battery	Ion Field Projection Battery	85 km
Ion Field Projection Battery	Ion Field Projection Battery	95 km
Large Artillery Battery	Large Artillery Battery	55 km
Medium Artillery Battery	Medium Artillery Battery	62 km
Medium Artillery Battery	Medium Artillery Battery	70 km
Medium Artillery Battery	Medium Artillery Battery	90 km
J115907 VIII - Moon 14	Moon	6,178 km
Personal Hangar Array	Personal Hangar Array	76 km
2	Ship Maintenance Array	75 km
1	Ship Maintenance Array	77 km
Warp Disruption Battery	Warp Disruption Battery	101 km
Warp Disruption Battery	Warp Disruption Battery	54 km
Warp Disruption Battery	Warp Disruption Battery	89 km
Warp Scrambling Battery	Warp Scrambling Battery	103 km
Warp Scrambling Battery	Warp Scrambling Battery	113 km
Warp Scrambling Battery	Warp Scrambling Battery	52 km
Warp Scrambling Battery	Warp Scrambling Battery	61 km
Warp Scrambling Battery	Warp Scrambling Battery	79 km
Warp Scrambling Battery	Warp Scrambling Battery	82 km
Warp Scrambling Battery	Warp Scrambling Battery	86 km
White Noise Generation Battery	White Noise Generation Battery	106 km
White Noise Generation Battery	White Noise Generation Battery	108 km
White Noise Generation Battery	White Noise Generation Battery	81 km

**Comment by Zumochi** [comment] 2015-09-22 17:57
It seems to be a specific issue with Angel Control Towers. During the past few days I have had the same problem (no POS on D-scan) with those towers. Change them to Minmatar or whatever and it works.

**Comment by neosilver-gk** [comment] 2015-10-09 09:23
Ok, I've found the issue in the EVE-datadump. There are two entries for Angel Control Tower in invTypes (typeID: 3591 and typeID:27539). The first dose belong to the marketGroupID: "Null" and that cause the exit without value. 

I think we now able to solve this CCP mistake.

**Comment by Zumochi** [comment] 2015-10-09 09:45
Would be good to file a bug report to CCP as well. 



—

**Comment by neosilver-gk** [comment] 2015-10-09 10:12
It was a joke. I think it works as designed. The first entry has a different groupID (319) and this is a "Large Collidable Structure". For example the groupID of all towers is 365 "Control Tower".

**Comment by Zumochi** [comment] 2015-10-09 10:36
Ohhhhh derp. 



—

**Comment by Maarten28** [comment] 2016-01-02 00:50
Resolved in PR #219

**Closed** 2016-01-06 20:04 UTC
