### ISSUE TITLE
[Issue] Adding POSes with Drug Labs Fails

### ISSUE THREAD

**Issue by AceMgy** [evewspace/eve-wspace#199] opened 2015-08-27 06:01 UTC
Reproduction:  Use this pastebin of a specific pos http://pastebin.com/jDuDHrEj
Remove the drug lab entry (for convenience http://pastebin.com/FHyRmRGt )
Then it works.

Pastebin of the error it spits out http://pastebin.com/3AQfX5Ha

**Comment by Zumochi** [comment] 2015-08-27 06:35
Fairly sure this is a duplicate of #196

**Comment by marbindrakon** [comment] 2015-08-27 07:31
The instance you're using wasn't updated to the latest build. It should be fixed now.

**Closed by marbindrakon** 2015-08-27 07:31 UTC
